name: type-check

on:
  pull_request:
    branches: [ main ]

jobs:
  type-check:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout commit
        uses: actions/checkout@v3
      - name: Install nodejs version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run type check
        run: npm run type-check
